package com.buyit.buyit.utils

object Constant {
    const val SHOP = "shop"
    const val SHOP_NAME = "shopName"
    const val SHOP_ID = "shopId"
    const val ID = "id"
    const val USER = "user"
    const val CUSTOMER = "customer"
    const val STATUS = "status"
    const val LOCATION = "location"
    const val SHUT_DOWN = "Shut Down"
    const val OPEN = "Open"
    const val CLOSE = "Close"
    const val KEY = "key"
    const val KEY_SHOP = "key_shop"
    const val DONE = "done"
    const val VERIFICATION_STATUS = "verificationStatus"
    const val CATEGORY_NAME = "categoryName"
    const val SHOP_CATEGORY = "shopCategory"
    const val LOGIN_SUCCESS = "0000"
    const val SUCCESS = "success"
    const val SPF = "sharedPreferences"
    const val RC_SIGN_IN = 100
    const val PRODUCT = "product"
    const val PRODUCT_CATEGORY_ID = "productCategoryId"
    const val PRODUCT_CATEGORY_NAME = "productCategoryName"
    const val CATEGORY = "category"
    const val NAME = "name"
    const val PRICE = "price"
    const val QUANTITY = "quantity"
    const val TOTAL_COUNT = "totalCount"
    const val UNIT = "unit"
    const val URL = "url"
    const val ORDER_LIST = "order_list"

}